import type { SessionEventDurable, V2Event } from "@opencode/client";

type SessionEvent = Extract<V2Event | SessionEventDurable, { type: `session.${string}` }>;

// Deferred variants retain their full native data for the later lifecycle and
// accounting tasks. Ignored variants have no supported T3 projection; in
// particular, internal cumulative usage must not masquerade as turn accounting.
export const openCodeNativeEventDisposition = {
  "session.created": "translated",
  "session.agent.selected": "deferred",
  "session.model.selected": "translated",
  "session.moved": "ignored",
  "session.renamed": "ignored",
  "session.metadata.updated": "ignored",
  "session.permissions": "ignored",
  "session.viewed": "ignored",
  "session.usage.updated": "translated",
  "session.deleted": "ignored",
  "session.forked": "ignored",
  "session.inbox.delivered": "translated",
  "session.inbox.enqueued": "translated",
  "session.inbox.cancelled": "translated",
  "session.inbox.delivery.changed": "deferred",
  "session.execution.started": "translated",
  "session.execution.succeeded": "translated",
  "session.execution.failed": "translated",
  "session.execution.interrupted": "translated",
  "session.instructions.updated": "ignored",
  "session.synthetic": "translated",
  "session.skill.activated": "deferred",
  "session.shell.started": "deferred",
  "session.shell.ended": "deferred",
  "session.step.started": "translated",
  "session.step.streamed": "translated",
  "session.step.ended": "translated",
  "session.step.failed": "translated",
  "session.text.started": "translated",
  "session.text.delta": "translated",
  "session.text.ended": "translated",
  "session.reasoning.started": "translated",
  "session.reasoning.delta": "translated",
  "session.reasoning.ended": "translated",
  "session.tool.input.started": "translated",
  "session.tool.input.delta": "translated",
  "session.tool.input.ended": "translated",
  "session.tool.called": "translated",
  "session.tool.progress": "translated",
  "session.tool.success": "translated",
  "session.tool.failed": "translated",
  "session.retry.scheduled": "deferred",
  "session.compaction.started": "translated",
  "session.compaction.delta": "deferred",
  "session.compaction.ended": "translated",
  "session.compaction.failed": "translated",
  "session.revert.staged": "ignored",
  "session.revert.cleared": "ignored",
  "session.revert.committed": "ignored",
  "session.usage.recorded": "translated",
  "session.message.content.updated": "ignored",
  "session.status": "ignored",
  "session.idle": "ignored",
} as const satisfies Record<SessionEvent["type"], "translated" | "deferred" | "ignored">;
